// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUXQ9y4l_d5Cn8Ehqnf9OjQ_dOgm0-pxs',
    appId: '1:861953191130:web:624753bf182439c9a989e3',
    messagingSenderId: '861953191130',
    projectId: 'zain-ashraf-1st',
    authDomain: 'zain-ashraf-1st.firebaseapp.com',
    storageBucket: 'zain-ashraf-1st.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5Lh5jDppEIk7jGZCeG5u-NupPqPBaZXA',
    appId: '1:861953191130:android:d0b19793150bc5f8a989e3',
    messagingSenderId: '861953191130',
    projectId: 'zain-ashraf-1st',
    storageBucket: 'zain-ashraf-1st.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdwKvHZeDFzXkUVadOr6zgCZea0lAN3EU',
    appId: '1:861953191130:ios:8537e05c77cc46d8a989e3',
    messagingSenderId: '861953191130',
    projectId: 'zain-ashraf-1st',
    storageBucket: 'zain-ashraf-1st.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdwKvHZeDFzXkUVadOr6zgCZea0lAN3EU',
    appId: '1:861953191130:ios:8537e05c77cc46d8a989e3',
    messagingSenderId: '861953191130',
    projectId: 'zain-ashraf-1st',
    storageBucket: 'zain-ashraf-1st.firebasestorage.app',
    iosBundleId: 'com.example.semesterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUXQ9y4l_d5Cn8Ehqnf9OjQ_dOgm0-pxs',
    appId: '1:861953191130:web:03070152eeb4ffe3a989e3',
    messagingSenderId: '861953191130',
    projectId: 'zain-ashraf-1st',
    authDomain: 'zain-ashraf-1st.firebaseapp.com',
    storageBucket: 'zain-ashraf-1st.firebasestorage.app',
  );

}